--------------------------------------------------------
--  Datei erstellt -Sonntag-Mai-19-2019   
--------------------------------------------------------
DROP TABLE "PIZZERIA"."Adresse" cascade constraints;
DROP TABLE "PIZZERIA"."Artikel" cascade constraints;
DROP TABLE "PIZZERIA"."Artikelgrößen" cascade constraints;
DROP TABLE "PIZZERIA"."Artikelgrößen_Rabatt" cascade constraints;
DROP TABLE "PIZZERIA"."Beschaffungseinheit" cascade constraints;
DROP TABLE "PIZZERIA"."Bestelldetails" cascade constraints;
DROP TABLE "PIZZERIA"."Bestellung" cascade constraints;
DROP TABLE "PIZZERIA"."Kunde" cascade constraints;
DROP TABLE "PIZZERIA"."Lieferung" cascade constraints;
DROP TABLE "PIZZERIA"."Lieferungsdetails" cascade constraints;
DROP TABLE "PIZZERIA"."Rabatt" cascade constraints;
DROP TABLE "PIZZERIA"."Rechnung" cascade constraints;
DROP TABLE "PIZZERIA"."Rezept" cascade constraints;
DROP TABLE "PIZZERIA"."Rezeptdetails" cascade constraints;
DROP TABLE "PIZZERIA"."Warenbestand" cascade constraints;
DROP TABLE "PIZZERIA"."Zahlungsbedingung" cascade constraints;
DROP TABLE "PIZZERIA"."Zutat" cascade constraints;
--------------------------------------------------------
--  DDL for Table Adresse
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Adresse" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Adressart" VARCHAR2(20 BYTE), 
	"Straße" VARCHAR2(255 BYTE), 
	"Hausnummer" VARCHAR2(255 BYTE), 
	"PLZ" VARCHAR2(255 BYTE), 
	"Ort" VARCHAR2(255 BYTE), 
	"Land" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Artikel
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Artikel" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Artikel" VARCHAR2(255 BYTE), 
	"Artikelbeschreibung" CLOB, 
	"Preis" VARCHAR2(20 BYTE), 
	"FK_Rezept" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" 
 LOB ("Artikelbeschreibung") STORE AS BASICFILE (
  TABLESPACE "USER01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Artikelgrößen
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Artikelgrößen" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Artikel" VARCHAR2(20 BYTE), 
	"Größe" VARCHAR2(20 BYTE), 
	"Kundenpreis" VARCHAR2(20 BYTE), 
	"Einkaufspreis" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Artikelgrößen_Rabatt
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Artikelgrößen_Rabatt" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Artikelgrößen" VARCHAR2(20 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Beschaffungseinheit
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Beschaffungseinheit" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Menge" VARCHAR2(20 BYTE), 
	"Mengeneinheit" VARCHAR2(255 BYTE), 
	"Ware" VARCHAR2(255 BYTE), 
	"Beschaffungspreis" VARCHAR2(20 BYTE), 
	"Mwst_Satz" VARCHAR2(20 BYTE), 
	"Mwst" VARCHAR2(20 BYTE), 
	"gültig_von" DATE, 
	"gültig_bis" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Bestelldetails
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Bestelldetails" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Bestellung" VARCHAR2(20 BYTE), 
	"Menge" VARCHAR2(20 BYTE), 
	"Mengeneinheit" VARCHAR2(255 BYTE), 
	"FK_Artikel" VARCHAR2(255 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Bestellung
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Bestellung" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Lieferant" VARCHAR2(20 BYTE), 
	"FK_Kunde" VARCHAR2(20 BYTE), 
	"FK_Lieferaddresse" VARCHAR2(20 BYTE), 
	"FK_Rechnungsadresse" VARCHAR2(20 BYTE), 
	"Bestelldatum" DATE, 
	"Bestellart" VARCHAR2(255 BYTE), 
	"Bestellstatus" VARCHAR2(255 BYTE), 
	"FK_Rabatt" VARCHAR2(255 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Kunde
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Kunde" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Kundenart" VARCHAR2(20 BYTE), 
	"Firmenname" VARCHAR2(255 BYTE), 
	"Titel" VARCHAR2(255 BYTE), 
	"Vorname" VARCHAR2(255 BYTE), 
	"Nachname" VARCHAR2(255 BYTE), 
	"FK_Lieferaddresse" VARCHAR2(20 BYTE), 
	"FK_Rechnungsaddresse" VARCHAR2(20 BYTE), 
	"Selbstabholer" VARCHAR2(5 BYTE), 
	"Stammkunde" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Lieferung
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Lieferung" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Lieferant" VARCHAR2(20 BYTE), 
	"FK_Kunde" VARCHAR2(20 BYTE), 
	"FK_Lieferadresse" VARCHAR2(20 BYTE), 
	"Bestelldatum" DATE, 
	"geplantes_Lieferdatum" DATE, 
	"Lieferdatum" DATE, 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE), 
	"Lieferstatus" VARCHAR2(255 BYTE), 
	"Grund für Nichtlieferung" CLOB, 
	"Bemerkung" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" 
 LOB ("Grund für Nichtlieferung") STORE AS BASICFILE (
  TABLESPACE "USER01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Bemerkung") STORE AS BASICFILE (
  TABLESPACE "USER01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Lieferungsdetails
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Lieferungsdetails" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Lieferung" VARCHAR2(20 BYTE), 
	"Artikelanzahl" VARCHAR2(20 BYTE), 
	"FK_Artikel" VARCHAR2(20 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Rabatt
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Rabatt" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Bedingung" VARCHAR2(255 BYTE), 
	"Fixrabatt" VARCHAR2(20 BYTE), 
	"Prozent" VARCHAR2(20 BYTE), 
	"Beschreibung" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" 
 LOB ("Beschreibung") STORE AS BASICFILE (
  TABLESPACE "USER01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Rechnung
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Rechnung" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Lieferant" VARCHAR2(20 BYTE), 
	"FK_Kunde" VARCHAR2(20 BYTE), 
	"FK_Rechnungsadresse" VARCHAR2(20 BYTE), 
	"FK_Lieferadresse" VARCHAR2(20 BYTE), 
	"Bestelldatum" DATE, 
	"Rechnungsdatum" DATE, 
	"Lieferdatum" DATE, 
	"FK_Zahlungsbedingungen" VARCHAR2(20 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Rezept
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Rezept" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Artikel" VARCHAR2(20 BYTE), 
	"Beschreibung" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" 
 LOB ("Beschreibung") STORE AS BASICFILE (
  TABLESPACE "USER01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Rezeptdetails
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Rezeptdetails" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Rezept" VARCHAR2(255 BYTE), 
	"Menge" VARCHAR2(20 BYTE), 
	"Mengeneinheit" VARCHAR2(255 BYTE), 
	"Zutat" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Warenbestand
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Warenbestand" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Zugang_Menge" VARCHAR2(20 BYTE), 
	"Zugang_Mengeneinheit" VARCHAR2(255 BYTE), 
	"Zugang_FK_Ware" VARCHAR2(20 BYTE), 
	"Preis" VARCHAR2(20 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE), 
	"Abgang_Menge" VARCHAR2(20 BYTE), 
	"Abgang_Mengeneinheit" VARCHAR2(255 BYTE), 
	"Abgang_FK_Zutaten" VARCHAR2(20 BYTE), 
	"Datum" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Zahlungsbedingung
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Zahlungsbedingung" 
   (	"ID" VARCHAR2(20 BYTE), 
	"Zahlungsbedingung" VARCHAR2(255 BYTE), 
	"Tage" VARCHAR2(20 BYTE), 
	"Skonto_Prozent" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
--------------------------------------------------------
--  DDL for Table Zutat
--------------------------------------------------------

  CREATE TABLE "PIZZERIA"."Zutat" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FK_Rechnung" VARCHAR2(20 BYTE), 
	"Menge" VARCHAR2(20 BYTE), 
	"Mengeneinheit" VARCHAR2(255 BYTE), 
	"FK_Artikel" VARCHAR2(255 BYTE), 
	"Preis" VARCHAR2(20 BYTE), 
	"Mwst_Satz" VARCHAR2(20 BYTE), 
	"Mwst" VARCHAR2(20 BYTE), 
	"FK_Rabatt" VARCHAR2(20 BYTE), 
	"Rabatt" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER01" ;
