--------------------------------------------------------
--  Datei erstellt -Montag-Mai-20-2019   
--------------------------------------------------------
REM INSERTING into STAMMBAUM2.BILDER
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.BILDER_TAB
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.DEMO_CONSTRAINT_LOOKUP
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.ELTERN
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.EMP
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.FAMILIE
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.FAMILIE_BILD
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.GESCHWISTER
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.LEBENSPARTNER
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.LEBENSPARTNER_BILD
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.ORT
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON_BERUF
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON_BILD
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON_FAMILIE
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON_RELIGION
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.PERSON_WOHNORT
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.TEST
SET DEFINE OFF;
REM INSERTING into STAMMBAUM2.TREE_TAB
SET DEFINE OFF;
