--------------------------------------------------------
--  Datei erstellt -Sonntag-Mai-19-2019   
--------------------------------------------------------
DROP SEQUENCE "FLIGHT_DEV"."ADR_ADDRESS_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_ADDRESS_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ADR_CITY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_COUNTRY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_COUNTRY_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ARP_AIRPORT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ARP_AIRPORT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BAK_BANKACCOUNT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."COM_COMPANY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."CON_CONTACT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."FLIGHT_DEVADR_CITY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_REL_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ";
DROP TABLE "FLIGHT_DEV"."ADR_ADDRESS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ADR_CITY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ADR_COUNTRY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE_MAINT_PROGR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ARP_AIRPORT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_RPM" cascade constraints;
DROP TABLE "FLIGHT_DEV"."COM_COMPANY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."CON_CONTACT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."COST_COST_GRP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_DOCUMENT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_USAGE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_COMMENTS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNT_REASONS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNTS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."GAL_GAIN_AND_LOSS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."HAN_HANGAR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."INV_INVOICE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."INV_INVOICE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."LAN_LANDING" cascade constraints;
DROP TABLE "FLIGHT_DEV"."MDT_MANDANT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ORG_ORG_UNIT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."PAY_PAYMENT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."PAY_PAYMENT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_AIRPORT_LOCATION" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_BORD_LOG_ENTRY_PAY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_CONTACT_ADDRESS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_CONTACT_BANKACCOUNT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_INV_PL_FLI_CH" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PAY_PLANE_FLI_CH" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER" cascade constraints;
DROP TABLE "FLIGHT_DEV"."RES_RESERVATION" cascade constraints;
DROP VIEW "FLIGHT_DEV"."V_ADR";
--------------------------------------------------------
--  DDL for Sequence ADR_ADDRESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_ADDRESS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_ADDRESS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_CITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_COUNTRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_COUNTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_COUNTRY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_COUNTRY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_MAINT_PROGR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_MAINT_PROGR_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ARP_AIRPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ARP_AIRPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ARP_AIRPORT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ARP_AIRPORT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAK_BANKACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAK_BANKACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAK_BANKACCOUNT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COM_COMPANY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."COM_COMPANY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CON_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."CON_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_USAGE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLIGHT_DEVADR_CITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."FLIGHT_DEVADR_CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_REL_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_REL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADR_ADDRESS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_ADDRESS" 
   (	"PK_ADR_ADDRESS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"STREET" VARCHAR2(4000 BYTE), 
	"STREET_NO" VARCHAR2(20 BYTE), 
	"ZIP_CODE" VARCHAR2(20 BYTE), 
	"FK_ADR_CITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADR_CITY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_CITY" 
   (	"PK_ADR_CITY" NUMBER, 
	"CITY" VARCHAR2(4000 BYTE), 
	"FK_ADR_COUNTRY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADR_COUNTRY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_COUNTRY" 
   (	"PK_ADR_COUNTRY" NUMBER, 
	"COUNTRY" VARCHAR2(4000 BYTE), 
	"PHONE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APL_ENGINE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" 
   (	"PK_APL_ENGINE_TYPE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"ENGINE_TYPE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APL_MAINT_PROGR
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" 
   (	"PK_APL_MAINT_PROGR" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"MAINT_PROGR" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APL_PLANE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_PLANE" 
   (	"PK_APL_PLANE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"PLANE_NO" VARCHAR2(20 BYTE), 
	"IMAGE" BLOB, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"FK_APL_PLANE_MODELL" VARCHAR2(20 BYTE), 
	"FK_APL_ENGINE_TYPE" NUMBER, 
	"CABIN_OV_13000_FT" VARCHAR2(4000 CHAR), 
	"BORD_00" VARCHAR2(4000 CHAR), 
	"BOARDING_OPPORTUNITY" NUMBER, 
	"CRUISING_SPEED_HG_20000_FT" NUMBER, 
	"CRUISING_SPEED_UNIT" VARCHAR2(4000 CHAR), 
	"WEIGHT_KERB_KG" NUMBER, 
	"WEIGHT_TAKEOFF_MAX_KG" NUMBER, 
	"PERMITTED_LOAD_KG" NUMBER, 
	"CNT_PASSENGERS_MAX" NUMBER, 
	"FUEL_TANK_SIZE_L" NUMBER, 
	"CONSUMPTION_L" NUMBER, 
	"RANGE_AVERAGE_FT" NUMBER, 
	"DIST_TAKE_OFF_FT" NUMBER, 
	"DIST_LANDING_FT" NUMBER, 
	"FK_APL_MAINT_PROGR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table APL_PLANE_MAINT_PROGR
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_PLANE_MAINT_PROGR" 
   (	"PK_APL_PLANE_MAINT_PROGR" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_APL_MAINT_PROGR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APL_PLANE_MODELL
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" 
   (	"PK_APL_PLANE_MODELL" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"MODELL_NO" VARCHAR2(20 BYTE), 
	"FK_APL_PLANE_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APL_PLANE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" 
   (	"PK_APL_PLANE_TYPE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"PLANE_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ARP_AIRPORT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ARP_AIRPORT" 
   (	"PK_ARP_AIRPORT" NUMBER, 
	"AIRPORT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BAK_BANKACCOUNT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" 
   (	"PK_BAK_BANKACCOUNT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"BANK" VARCHAR2(20 BYTE), 
	"IBAN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BAK_BANKACCOUNT_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" 
   (	"PK_BANKACCOUNT_TYPE" NUMBER, 
	"BANK_ACCOUNT_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOR_BORD_LOG
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BOR_BORD_LOG" 
   (	"PK_BOR_BORDLOG" VARCHAR2(20 BYTE), 
	"BORD_LOG" VARCHAR2(400 BYTE), 
	"BORD_LOG_DATE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOR_BORD_LOG_ENTRY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY" 
   (	"PK_BORD_LOG_ENTRY" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_FLI_FLIGHT" NUMBER, 
	"ENTRY_DATE" DATE, 
	"PIC" VARCHAR2(20 BYTE), 
	"T_O_TIME" DATE, 
	"LDG_TIME" DATE, 
	"CHARGES" VARCHAR2(20 BYTE), 
	"EDMA" VARCHAR2(20 BYTE), 
	"ARRIVAL" VARCHAR2(20 BYTE), 
	"FK_BORD_LOG_ENTRY_GRP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOR_BORD_LOG_ENTRY_GRP
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP" 
   (	"PK_BORD_LOG_ENTRY_GRP" NUMBER, 
	"GROUP_NAME" VARCHAR2(4000 BYTE), 
	"FK_MDT_MANDANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOR_BORD_LOG_ENTRY_RPM
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_RPM" 
   (	"PK_BORD_LOG_ENTRY_RPM" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_BOR_BORD_LOG_ENTRY" NUMBER, 
	"HOBBS" VARCHAR2(20 BYTE), 
	"RPM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COM_COMPANY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."COM_COMPANY" 
   (	"PK_COM_COMPANY" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"COMPANY_LOCATION" VARCHAR2(4000 BYTE), 
	"FK_ADR_ADRESS" NUMBER, 
	"FK_COM_COMPANY_TYPE" NUMBER, 
	"FK_CON_CONTACT_MAIN" NUMBER, 
	"VALID" VARCHAR2(20 BYTE), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CON_CONTACT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."CON_CONTACT" 
   (	"PK_CON_CONTACT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_CON_CONTACT_TYPE" NUMBER, 
	"FK_ADR_ADRESS" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(4000 BYTE), 
	"COUNTRY_PREFIX" VARCHAR2(20 BYTE), 
	"PHONE_NO" VARCHAR2(20 BYTE), 
	"BIRTH_DAY" DATE, 
	"ACTIVE" NUMBER, 
	"ACTIVE_FROM" DATE, 
	"ACTIVE_TO" DATE, 
	"CREATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_AT" DATE, 
	"MDOIFIED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COST_COST_GRP
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."COST_COST_GRP" 
   (	"PK_COST_COST_GRP" NUMBER, 
	"COST_GRP_NAME" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOC_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."DOC_DOCUMENT" 
   (	"PK_DOC_DOCUMENT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_DOC_DOCUMENT_TYPE" NUMBER, 
	"FK_DOC_USAGE_TYPE" NUMBER, 
	"DOCUMENT_TITLE" VARCHAR2(20 BYTE), 
	"DOCUMENT" BLOB, 
	"VALID" NUMBER, 
	"VALID_UNTIL" VARCHAR2(20 BYTE), 
	"DOCUMENT_NR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DOC_DOCUMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE" 
   (	"PK_DOC_DOCUMENT_TYPE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"DOC_DOCUMENT_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOC_USAGE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."DOC_USAGE_TYPE" 
   (	"PK_DOC_USAGE_TYPE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"USAGE_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FLI_FLIGHT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."FLI_FLIGHT" 
   (	"PK_FLI_FLIGHT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"DEPARTURE" VARCHAR2(20 BYTE), 
	"ARRIVAL" VARCHAR2(20 BYTE), 
	"DEPARTURE_TIME" NUMBER, 
	"ARRIVAL_TIME" NUMBER, 
	"DURATION" DATE, 
	"ADDITIONAL_TIMESLOTS" DATE, 
	"FK_ADDITIONAL_TIMESLOTTYPE" NUMBER, 
	"FK_APL_PLANE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FLI_FLIGHT_COMMENTS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."FLI_FLIGHT_COMMENTS" 
   (	"PK_FLI_FLIGHT_COMMENTS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"COMM" CLOB, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE, 
	"MODIFY_AT" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMM") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FLI_FLIGHT_DISCOUNT_REASONS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNT_REASONS" 
   (	"PK_FLI_FLIGHT_DISCOUNT_REASONS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"DISCOUNT_REASON" CLOB, 
	"VALID" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DISCOUNT_REASON") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FLI_FLIGHT_DISCOUNTS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNTS" 
   (	"PK_FLI_FLIGHT_DISCOUNTS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"DISCOUNT_VALUE" NUMBER, 
	"FK_DISCOUNT_REASON" NUMBER, 
	"FK_FLI_FLIGHT" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER, 
	"HOURLY_RATE" NUMBER, 
	"HOURS" NUMBER, 
	"MINUTES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GAL_GAIN_AND_LOSS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."GAL_GAIN_AND_LOSS" 
   (	"PK_GAL_GAIN_AND_LOSS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"VERSION" NUMBER, 
	"FIN_YEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HAN_HANGAR
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."HAN_HANGAR" 
   (	"PK_HAN_HANGAR" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"FK_ADR_ADRESS" NUMBER, 
	"FK_CON_CONTACT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INV_INVOICE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."INV_INVOICE" 
   (	"PK_INV_INVOICE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER, 
	"INVOICE_DATE" DATE, 
	"IN_OUT" NUMBER, 
	"RECIEPIENT" NUMBER, 
	"BRUT_VALUE" NUMBER, 
	"TAX" NUMBER, 
	"TAX_RATE" NUMBER, 
	"NET_VALUE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INV_INVOICE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."INV_INVOICE_TYPE" 
   (	"PK_INV_INVOICE_TYPE" NUMBER, 
	"INVOICE_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LAN_LANDING
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."LAN_LANDING" 
   (	"PK_LAN_LANDING" NUMBER, 
	"MDT_MANDANT" NUMBER, 
	"FK_ARP_AIRPORT" NUMBER, 
	"FK_FLI_FLIGHT" NUMBER, 
	"PRICE_INVOICED" NUMBER, 
	"PRICE_PAYED" NUMBER, 
	"PRICE_CALCULATED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MDT_MANDANT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."MDT_MANDANT" 
   (	"PK_MDT_MANDANT" NUMBER, 
	"MANDANT" VARCHAR2(4000 BYTE), 
	"FK_ORG_ORG_UNIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORG_ORG_UNIT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ORG_ORG_UNIT" 
   (	"PK_ORG_ORG_UNIT" NUMBER, 
	"FK_MDT_MANDANT" VARCHAR2(20 BYTE), 
	"COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"ORG_UNIT_NAME" VARCHAR2(4000 BYTE), 
	"FK_CON_CONTACT" NUMBER, 
	"ACTIVE" NUMBER, 
	"ACTIVE_FROM" DATE, 
	"ACTIVE_TO" DATE, 
	"CREATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_AT" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"FK_ORG_ORG_UNIT_TYPE" NUMBER, 
	"FK_ORG_ORG_UNIT_REL_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAY_PAYMENT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."PAY_PAYMENT" 
   (	"PK_PAY_PAYMENT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"VALUE" VARCHAR2(20 BYTE), 
	"FK_PAY_PAYMENT_TYPE" NUMBER, 
	"PAY_DATE" NUMBER, 
	"BOOKING_DATE" NUMBER, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFY_AT" DATE, 
	"FK_APL_PLANE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAY_PAYMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."PAY_PAYMENT_TYPE" 
   (	"PAY_PAYMENT_TYPE" NUMBER, 
	"PAYMENT_TYPE" VARCHAR2(4000 BYTE), 
	"FK_MDT_MANDANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_AIRPORT_LOCATION
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_AIRPORT_LOCATION" 
   (	"PK_REL_AIRPORT_LOCATION" NUMBER, 
	"FK_ARP_AIRPORT" NUMBER, 
	"FK_LOC_LOCATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_BORD_LOG_ENTRY_PAY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_BORD_LOG_ENTRY_PAY" 
   (	"FK_BORD_LOG_ENTRY_PAY" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_BORD_LOG_ENTRY" NUMBER, 
	"FK_PAYNENT" NUMBER, 
	"ADDITIONAL_COSTS" NUMBER, 
	"CREDIT_NOTE" NUMBER, 
	"CREDIT_NOTE_CURRENCY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_CONTACT_ADDRESS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_CONTACT_ADDRESS" 
   (	"PK_REL_CONTACT_ADDRESS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_CON_CONTACT" NUMBER, 
	"FK_ADR_ADDRESS" NUMBER, 
	"FK_ADR_COUNTRY" NUMBER, 
	"PHONE_NO" VARCHAR2(4000 BYTE), 
	"EMAIL" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_CONTACT_BANKACCOUNT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_CONTACT_BANKACCOUNT" 
   (	"PK_CONTACT_BANKACCOUNT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_BAK_BANKACCOUNT" NUMBER, 
	"VALID" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"FK_CON_CONTACT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_INV_PL_FLI_CH
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_INV_PL_FLI_CH" 
   (	"PK_INV_PL_FLI_CH" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_INV_INVOICE" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_FLI_FLIGHT" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER, 
	"FK_REL_PLANE_FLIGHT" NUMBER, 
	"FK_REL_PLANE_FLIGHT_CHARTERER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FLIGHT_DEV"."REL_INV_PL_FLI_CH"."FK_CST_CUSTOMER" IS 'Charterer';
--------------------------------------------------------
--  DDL for Table REL_ORG_UNIT_CONTACT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT" 
   (	"PK_ORG_UNIT_CONTACT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_ORG_ORG_UNIT" NUMBER, 
	"FK_CON_CONTACT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_PAY_PLANE_FLI_CH
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_PAY_PLANE_FLI_CH" 
   (	"PK_PAY_PLANE_FLI_CH" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_PAY_PAYMENT" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_REL_PLANE_FLIGHT_CHARTERER" NUMBER, 
	"FK_APL_FLIGHT" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER, 
	"FK_REL_PLANE_FLIGHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_PLANE_FLIGHT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT" 
   (	"PK_PLANE_FLIGHT" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_APL_PLANE" NUMBER, 
	"FK_FLI_FLIGHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REL_PLANE_FLIGHT_CHARTERER
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER" 
   (	"FK_REL_PLANE_FLIGHT_CHARTERER" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FK_REL_PLANE_FLIGHT" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RES_RESERVATION
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."RES_RESERVATION" 
   (	"PK_RES_RESERVATION" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"VALID" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"FK_MAI_STATE" DATE, 
	"CREATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"COLUMN1" DATE, 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"FK_APL_PLANE" NUMBER, 
	"FK_CST_CUSTOMER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View V_ADR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLIGHT_DEV"."V_ADR" ("PK_ADR_ADDRESS", "FK_MDT_MANDANT", "STREET", "STREET_NO", "ZIP_CODE", "FK_ADR_CITY", "PK_ADR_CITY", "CITY", "FK_ADR_COUNTRY", "PK_ADR_COUNTRY", "COUNTRY", "PHONE_CODE") AS 
  select PK_ADR_ADDRESS,FK_MDT_MANDANT,STREET,STREET_NO,ZIP_CODE,FK_ADR_CITY,PK_ADR_CITY,CITY,FK_ADR_COUNTRY,PK_ADR_COUNTRY,COUNTRY,PHONE_CODE
 from adr_address adr 
   left join adr_city cit on adr.fk_adr_city = cit.pk_adr_city
   left join adr_country cou on cit.fk_adr_country =cou.pk_adr_country
;
--------------------------------------------------------
--  DDL for Index APL_PLANE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."APL_PLANE_PK" ON "FLIGHT_DEV"."APL_PLANE" ("PK_APL_PLANE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BAK_BANKACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."BAK_BANKACCOUNT_PK" ON "FLIGHT_DEV"."BAK_BANKACCOUNT" ("PK_BAK_BANKACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADR_CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."ADR_CITY_PK" ON "FLIGHT_DEV"."ADR_CITY" ("PK_ADR_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APL_MAINT_PROGR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."APL_MAINT_PROGR_PK" ON "FLIGHT_DEV"."APL_MAINT_PROGR" ("PK_APL_MAINT_PROGR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ARP_AIRPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."ARP_AIRPORT_PK" ON "FLIGHT_DEV"."ARP_AIRPORT" ("PK_ARP_AIRPORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APL_PLANE_MODELL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."APL_PLANE_MODELL_PK" ON "FLIGHT_DEV"."APL_PLANE_MODELL" ("PK_APL_PLANE_MODELL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APL_PLANE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."APL_PLANE_TYPE_PK" ON "FLIGHT_DEV"."APL_PLANE_TYPE" ("PK_APL_PLANE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADR_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."ADR_ADDRESS_PK" ON "FLIGHT_DEV"."ADR_ADDRESS" ("PK_ADR_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORG_ORG_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."ORG_ORG_UNIT_PK" ON "FLIGHT_DEV"."ORG_ORG_UNIT" ("PK_ORG_ORG_UNIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADR_COUNTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."ADR_COUNTRY_PK" ON "FLIGHT_DEV"."ADR_COUNTRY" ("PK_ADR_COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APL_ENGINE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."APL_ENGINE_TYPE_PK" ON "FLIGHT_DEV"."APL_ENGINE_TYPE" ("PK_APL_ENGINE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOR_BORD_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."BOR_BORD_LOG_PK" ON "FLIGHT_DEV"."BOR_BORD_LOG" ("PK_BOR_BORDLOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BAK_BANKACCOUNT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_PK" ON "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" ("PK_BANKACCOUNT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MDT_MANDANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHT_DEV"."MDT_MANDANT_PK" ON "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ADR_ADDRESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."ADR_ADDRESS_TRG" 
BEFORE INSERT ON ADR_ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_ADR_ADDRESS IS NULL THEN
      SELECT ADR_ADDRESS_SEQ1.NEXTVAL INTO :NEW.PK_ADR_ADDRESS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."ADR_ADDRESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADR_CITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."ADR_CITY_TRG" 
BEFORE INSERT ON ADR_CITY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_ADR_CITY IS NULL THEN
      SELECT ADR_CITY_SEQ.NEXTVAL INTO :NEW.PK_ADR_CITY FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."ADR_CITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADR_COUNTRY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."ADR_COUNTRY_TRG" 
BEFORE INSERT ON ADR_COUNTRY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_ADR_COUNTRY IS NULL THEN
      SELECT ADR_COUNTRY_SEQ1.NEXTVAL INTO :NEW.PK_ADR_COUNTRY FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."ADR_COUNTRY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger APL_MAINT_PROGR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."APL_MAINT_PROGR_TRG" 
BEFORE INSERT ON APL_MAINT_PROGR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_APL_MAINT_PROGR IS NULL THEN
      SELECT APL_MAINT_PROGR_SEQ1.NEXTVAL INTO :NEW.PK_APL_MAINT_PROGR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."APL_MAINT_PROGR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger APL_PLANE_MODELL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."APL_PLANE_MODELL_TRG" 
BEFORE INSERT ON APL_PLANE_MODELL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FK_MDT_MANDANT IS NULL THEN
      SELECT APL_PLANE_MODELL_SEQ1.NEXTVAL INTO :NEW.FK_MDT_MANDANT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."APL_PLANE_MODELL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger APL_PLANE_MODELL_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."APL_PLANE_MODELL_TRG1" 
BEFORE INSERT ON APL_PLANE_MODELL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_APL_PLANE_MODELL IS NULL THEN
      SELECT APL_PLANE_MODELL_SEQ2.NEXTVAL INTO :NEW.PK_APL_PLANE_MODELL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."APL_PLANE_MODELL_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARP_AIRPORT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."ARP_AIRPORT_TRG" 
BEFORE INSERT ON ARP_AIRPORT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_ARP_AIRPORT IS NULL THEN
      SELECT ARP_AIRPORT_SEQ1.NEXTVAL INTO :NEW.PK_ARP_AIRPORT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."ARP_AIRPORT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BAK_BANKACCOUNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."BAK_BANKACCOUNT_TRG" 
BEFORE INSERT ON BAK_BANKACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."BAK_BANKACCOUNT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BAK_BANKACCOUNT_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_TRG" 
BEFORE INSERT ON BAK_BANKACCOUNT_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_BANKACCOUNT_TYPE IS NULL THEN
      SELECT BAK_BANKACCOUNT_TYPE_SEQ.NEXTVAL INTO :NEW.PK_BANKACCOUNT_TYPE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOR_BORD_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."BOR_BORD_LOG_TRG" 
BEFORE INSERT ON BOR_BORD_LOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."BOR_BORD_LOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MDT_MANDANT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FLIGHT_DEV"."MDT_MANDANT_TRG" 
BEFORE INSERT ON MDT_MANDANT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_MDT_MANDANT IS NULL THEN
      SELECT MDT_MANDANT_SEQ2.NEXTVAL INTO :NEW.PK_MDT_MANDANT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FLIGHT_DEV"."MDT_MANDANT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARP_AIRPORT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ARP_AIRPORT" ADD CONSTRAINT "ARP_AIRPORT_PK" PRIMARY KEY ("PK_ARP_AIRPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ARP_AIRPORT" MODIFY ("PK_ARP_AIRPORT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_PLANE_MODELL
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" ADD CONSTRAINT "APL_PLANE_MODELL_PK" PRIMARY KEY ("PK_APL_PLANE_MODELL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" MODIFY ("PK_APL_PLANE_MODELL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAK_BANKACCOUNT_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" ADD CONSTRAINT "BAK_BANKACCOUNT_TYPE_PK" PRIMARY KEY ("PK_BANKACCOUNT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" MODIFY ("PK_BANKACCOUNT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOR_BORD_LOG_ENTRY_RPM
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_RPM" MODIFY ("PK_BORD_LOG_ENTRY_RPM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_ENGINE_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" ADD CONSTRAINT "APL_ENGINE_TYPE_PK" PRIMARY KEY ("PK_APL_ENGINE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" MODIFY ("FK_MDT_MANDANT" NOT NULL ENABLE);
  ALTER TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" MODIFY ("PK_APL_ENGINE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOC_DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE" MODIFY ("PK_DOC_DOCUMENT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_MAINT_PROGR
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" ADD CONSTRAINT "APL_MAINT_PROGR_PK" PRIMARY KEY ("PK_APL_MAINT_PROGR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" MODIFY ("PK_APL_MAINT_PROGR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_PLANE_MAINT_PROGR
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_MAINT_PROGR" MODIFY ("PK_APL_PLANE_MAINT_PROGR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOR_BORD_LOG
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BOR_BORD_LOG" ADD CONSTRAINT "BOR_BORD_LOG_PK" PRIMARY KEY ("PK_BOR_BORDLOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."BOR_BORD_LOG" MODIFY ("PK_BOR_BORDLOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CON_CONTACT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."CON_CONTACT" MODIFY ("PK_CON_CONTACT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_PLANE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE" ADD CONSTRAINT "APL_PLANE_PK" PRIMARY KEY ("PK_APL_PLANE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_PLANE" MODIFY ("PK_APL_PLANE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MDT_MANDANT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."MDT_MANDANT" ADD CONSTRAINT "MDT_MANDANT_PK" PRIMARY KEY ("PK_MDT_MANDANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."MDT_MANDANT" MODIFY ("PK_MDT_MANDANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORG_ORG_UNIT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ORG_ORG_UNIT" ADD CONSTRAINT "ORG_ORG_UNIT_PK" PRIMARY KEY ("PK_ORG_ORG_UNIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ORG_ORG_UNIT" MODIFY ("PK_ORG_ORG_UNIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADR_COUNTRY
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ADR_COUNTRY" ADD CONSTRAINT "ADR_COUNTRY_PK" PRIMARY KEY ("PK_ADR_COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ADR_COUNTRY" MODIFY ("PK_ADR_COUNTRY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COM_COMPANY
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."COM_COMPANY" MODIFY ("PK_COM_COMPANY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOR_BORD_LOG_ENTRY_GRP
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP" MODIFY ("PK_BORD_LOG_ENTRY_GRP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAK_BANKACCOUNT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" ADD CONSTRAINT "BAK_BANKACCOUNT_PK" PRIMARY KEY ("PK_BAK_BANKACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" MODIFY ("PK_BAK_BANKACCOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APL_PLANE_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" ADD CONSTRAINT "APL_PLANE_TYPE_PK" PRIMARY KEY ("PK_APL_PLANE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" MODIFY ("PK_APL_PLANE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADR_ADDRESS
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ADR_ADDRESS" ADD CONSTRAINT "ADR_ADDRESS_PK" PRIMARY KEY ("PK_ADR_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ADR_ADDRESS" MODIFY ("PK_ADR_ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOC_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."DOC_DOCUMENT" MODIFY ("PK_DOC_DOCUMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADR_CITY
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ADR_CITY" ADD CONSTRAINT "ADR_CITY_PK" PRIMARY KEY ("PK_ADR_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ADR_CITY" MODIFY ("PK_ADR_CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOR_BORD_LOG_ENTRY
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY" MODIFY ("PK_BORD_LOG_ENTRY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADR_ADDRESS
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ADR_ADDRESS" ADD CONSTRAINT "ADR_ADDRESS_FK1" FOREIGN KEY ("FK_ADR_CITY")
	  REFERENCES "FLIGHT_DEV"."ADR_CITY" ("PK_ADR_CITY") ENABLE;
  ALTER TABLE "FLIGHT_DEV"."ADR_ADDRESS" ADD CONSTRAINT "ADR_ADDRESS_FK2" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADR_CITY
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."ADR_CITY" ADD CONSTRAINT "ADR_CITY_FK1" FOREIGN KEY ("FK_ADR_COUNTRY")
	  REFERENCES "FLIGHT_DEV"."ADR_COUNTRY" ("PK_ADR_COUNTRY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APL_ENGINE_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" ADD CONSTRAINT "APL_ENGINE_TYPE_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APL_MAINT_PROGR
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" ADD CONSTRAINT "APL_MAINT_PROGR_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APL_PLANE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE" ADD CONSTRAINT "APL_PLANE_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APL_PLANE_MODELL
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" ADD CONSTRAINT "APL_PLANE_MODELL_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" ADD CONSTRAINT "APL_PLANE_MODELL_FK2" FOREIGN KEY ("FK_APL_PLANE_TYPE")
	  REFERENCES "FLIGHT_DEV"."APL_PLANE_TYPE" ("PK_APL_PLANE_TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APL_PLANE_TYPE
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" ADD CONSTRAINT "APL_PLANE_TYPE_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BAK_BANKACCOUNT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" ADD CONSTRAINT "BAK_BANKACCOUNT_FK1" FOREIGN KEY ("FK_MDT_MANDANT")
	  REFERENCES "FLIGHT_DEV"."MDT_MANDANT" ("PK_MDT_MANDANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MDT_MANDANT
--------------------------------------------------------

  ALTER TABLE "FLIGHT_DEV"."MDT_MANDANT" ADD CONSTRAINT "MDT_MANDANT_FK1" FOREIGN KEY ("FK_ORG_ORG_UNIT")
	  REFERENCES "FLIGHT_DEV"."ORG_ORG_UNIT" ("PK_ORG_ORG_UNIT") ENABLE;
