--------------------------------------------------------
--  Datei erstellt -Samstag-Mai-25-2019   
--------------------------------------------------------
REM INSERTING into COMPANY.T_ABSCHLUSSTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ADRESSE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARBEITSTAGE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARBEITSZEITEN
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARTIKELBESTANDTEILE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARTIKELBESTANDTEILTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ARTIKELTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_AUFGABE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BANK
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BANKKONTO
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BELEG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BELEGART
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BELEGPOSITION
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BESTELLUNG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BUCH
SET DEFINE OFF;
REM INSERTING into COMPANY.T_BUENDELUNG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_COMP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_DAT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_EINSENDEAUFGABE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_EINSENDEAUFGABENSTATUS
SET DEFINE OFF;
REM INSERTING into COMPANY.T_FARBE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_GESCHAEFTSPARTNER
SET DEFINE OFF;
REM INSERTING into COMPANY.T_GESCHAEFTSPARTNERTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_HERSTELLER
SET DEFINE OFF;
REM INSERTING into COMPANY.T_IMP_BEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_IMP_KRE_062017
SET DEFINE OFF;
REM INSERTING into COMPANY.T_IMP_KTO_062017
SET DEFINE OFF;
REM INSERTING into COMPANY.T_INV_COMP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_INVENTARE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_INVENTARTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_KONTAKT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_KONTAKTTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_LAGERORT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_LEHRGANG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_LOCATION
SET DEFINE OFF;
REM INSERTING into COMPANY.T_LOCATION_TYPE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_MENGENEINHEIT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ORGANISATIONSEINHEIT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_ORT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PACKUNGSTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PERSON
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PLZ_ORT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PRODUKT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PROJEKT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_PRUEFUNG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_QUELLE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_QUELLENTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_RECHNUNG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_RECHNUNGSTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_ARTIKEL_ARTIKELTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BELEG_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BELEG_INVENTAR
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BELEG_LOCATION
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BELEGPOS_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BELEG_PRODUKT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BEL_KONT_ADR
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_BEL_VERBRAUCHSMAT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_GESCHAEFTSP_KONT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_GESCHAEFTSP_KUNR
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_INVENTAR_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_INVENTAR_INVENTARTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_INV_VERBRAUCHSMAT
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_KONTAKT_KONTAKTTYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_KONTAKTPERSON_ADRESSE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_LAGERORT_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_LOCATION_ADRESSE
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_PRODUKT_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_PRODUKT_ENTNAHME
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_RECHNG_STUNDEN
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_RECHNUNG_BELEG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_RECHNUNG_STUNDENZETTEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_REZEPT_ARTIKEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_STUNDEN_BELEG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_REL_STUNDENZETTEL_BELEG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_STD
SET DEFINE OFF;
REM INSERTING into COMPANY.T_STD_GROUP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_STEUERSATZ
SET DEFINE OFF;
REM INSERTING into COMPANY.T_STUNDENZETTEL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_TERMIN
SET DEFINE OFF;
REM INSERTING into COMPANY.T_VERBRAUCHSMATERIAL
SET DEFINE OFF;
REM INSERTING into COMPANY.T_VERBRAUCHSMAT_TYP
SET DEFINE OFF;
REM INSERTING into COMPANY.T_VERWENDUNGSZWECK
SET DEFINE OFF;
REM INSERTING into COMPANY.T_WARENBESTAND
SET DEFINE OFF;
REM INSERTING into COMPANY.T_WARENBEWEGUNG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_WARENEINGANG
SET DEFINE OFF;
REM INSERTING into COMPANY.T_WARENENTNAHME
SET DEFINE OFF;
